<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV38gtZT\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV38gtZT/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerV38gtZT.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerV38gtZT\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerV38gtZT\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'V38gtZT',
    'container.build_id' => '24307385',
    'container.build_time' => 1574354271,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV38gtZT');
