<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPkOMUwe\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPkOMUwe/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPkOMUwe.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPkOMUwe\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPkOMUwe\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'PkOMUwe',
    'container.build_id' => '22dd04a5',
    'container.build_time' => 1574355836,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPkOMUwe');
