<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOvqPgWw\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOvqPgWw/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOvqPgWw.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOvqPgWw\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerOvqPgWw\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'OvqPgWw',
    'container.build_id' => '34cf5482',
    'container.build_time' => 1574352493,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOvqPgWw');
